# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: 'window-server'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Installing Nuget tool'
- task: NuGetCommand@2
  displayName: 'Run Nuget Command'
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/Demo.csproj'
    feedsToUse: 'select'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet build'
#  inputs:
#    command: 'build'
#    projects: '**/Demo.csproj'
#    arguments: '--configuration $(BuildConfiguration)'
 
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    projects: |
     **/Demo.csproj
     !**/*SeleniumUiTests.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*UnitTest*.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: NuGetCommand@2
  displayName: 'Nuget pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/Demo.csproj'
    versioningScheme: 'off'


- task: NuGetCommand@2
  displayName: 'Feed Nuget pack'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '6d6a8a4d-9d44-483d-8cbf-152ef325cb31/b847245d-760f-4d19-983c-4342e5809905'